/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.1 		*/
/*  Created On : 22-dez-2020 20:29:14 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

DROP DATABASE IF EXISTS ist187225;
CREATE SCHEMA IF NOT EXISTS ist187225;
USE ist187225;

/* Create Tables */

CREATE TABLE `agent`
(
	`agent_name` VARCHAR(50) NOT NULL,
	`phone_number` INT NULL,
	`email` VARCHAR(50) NULL,
	`company` VARCHAR(50) NULL,
    `pass` VARCHAR(50) NULL,
	PRIMARY KEY (`agent_name` ASC)
)

;

CREATE TABLE `coach`
(
	`coach_name` VARCHAR(50) NOT NULL,
    `pass` VARCHAR(50) NULL,
	PRIMARY KEY (`coach_name` ASC)
)

;

CREATE TABLE `financial_info`
(
	`contract_id` INT NOT NULL,
	`contract_expiry_date` DATE NULL,
	`transfer_fee` INT NULL,
	`current_wage` INT NULL,
	`demanded_wage` INT NULL,
	`demanded_contract_length` INT NULL,
	`signing_fee` INT NULL,
	PRIMARY KEY (`contract_id` ASC)
)



;

CREATE TABLE `player`
(
	`player_name` VARCHAR(50) NOT NULL,
	`position` VARCHAR(50) NULL,
	`club` VARCHAR(50) NULL,
	`birth_date` DATE NULL,
	`dominant_foot` VARCHAR(50) NULL,
	`country` VARCHAR(50) NULL,
	`height` INT NULL,
	`weight` INT NULL,
	`international_caps` INT NULL,
	PRIMARY KEY (`player_name` ASC)
)

;

CREATE TABLE `provides`
(	
	`agent_name` VARCHAR(50) NOT NULL,
	`contract_id` INT NOT NULL,
	`player_name` VARCHAR(50) NOT NULL,
    `agent_fee` INT NULL,
	PRIMARY KEY (`agent_name` ASC, `contract_id` ASC, `player_name` ASC)
)

;

CREATE TABLE `refers_to`
(
	`coach_name` VARCHAR(50) NOT NULL,
	`sd_name` VARCHAR(50) NOT NULL,
	`player_name` VARCHAR(50) NOT NULL,
	PRIMARY KEY (`coach_name` ASC, `sd_name` ASC, `player_name` ASC)
)

;

CREATE TABLE `request`
(
	`request_id` INT NOT NULL,
	`position` VARCHAR(50) NULL,
	`coach_name` VARCHAR(50) NOT NULL,
	`scout_name` VARCHAR(50) NOT NULL,
    `p_requirements` VARCHAR(200) NULL,
	PRIMARY KEY (`request_id` ASC, `coach_name` ASC, `scout_name` ASC)
)

;

CREATE TABLE `scout`
(
	`scout_name` VARCHAR(50) NOT NULL,
	`league` VARCHAR(50) NULL,
	`country` VARCHAR(50) NULL,
    `pass` VARCHAR(50) NULL,
	PRIMARY KEY (`scout_name` ASC)
)

;

CREATE TABLE `scouting_report`
(
	`report_id` INT NOT NULL,
	`handling` INT NULL,
	`reflexes` INT NULL,
	`shooting` INT NULL,
	`passing` INT NULL,
	`tackling` INT NULL,
	`dribbling` INT NULL,
	`leadership` INT NULL,
	`positioning` INT NULL,
	`strength` INT NULL,
	`stamina` INT NULL,
	`speed` INT NULL,
	PRIMARY KEY (`report_id` ASC)
)

;

CREATE TABLE `sporting_director`
(
	`sd_name` VARCHAR(50) NOT NULL,
    `pass` VARCHAR(50) NULL,
	PRIMARY KEY (`sd_name` ASC)
)

;

CREATE TABLE `watches`
(
	`scout_name` VARCHAR(50) NOT NULL,
	`report_id` INT NOT NULL,
	`player_name` VARCHAR(50) NOT NULL,
	PRIMARY KEY (`scout_name` ASC, `report_id` ASC, `player_name` ASC)
)

;

CREATE TABLE `works_with`
(
	`coach_name` VARCHAR(50) NOT NULL,
	`sd_name` VARCHAR(50) NOT NULL,
	PRIMARY KEY (`coach_name` ASC, `sd_name` ASC)
)

;

/* Create Foreign Key Constraints */



ALTER TABLE `provides` 
 ADD 
	FOREIGN KEY (`agent_name`) REFERENCES `agent` (`agent_name`) 
    ON DELETE CASCADE
;

ALTER TABLE `provides` 
 ADD 
	FOREIGN KEY (`contract_id`) REFERENCES `financial_info` (`contract_id`) 
    ON DELETE CASCADE
;

ALTER TABLE `provides` 
 ADD 
	FOREIGN KEY (`player_name`) REFERENCES `player` (`player_name`) 
    ON DELETE CASCADE
;

ALTER TABLE `refers_to` 
 ADD 
	FOREIGN KEY (`coach_name`) REFERENCES `coach` (`coach_name`) 
    ON DELETE CASCADE
;

ALTER TABLE `refers_to` 
 ADD 
	FOREIGN KEY (`player_name`) REFERENCES `player` (`player_name`) 
    ON DELETE CASCADE
;

ALTER TABLE `refers_to` 
 ADD 
	FOREIGN KEY (`sd_name`) REFERENCES `sporting_director` (`sd_name`) 
    ON DELETE CASCADE
;

ALTER TABLE `request` 
 ADD 
	FOREIGN KEY (`coach_name`) REFERENCES `coach` (`coach_name`) 
    ON DELETE CASCADE
;

ALTER TABLE `request` 
 ADD 
	FOREIGN KEY (`scout_name`) REFERENCES `scout` (`scout_name`) 
;

ALTER TABLE `watches` 
 ADD 
	FOREIGN KEY (`player_name`) REFERENCES `player` (`player_name`) 
    ON DELETE CASCADE
;

ALTER TABLE `watches` 
 ADD 
	FOREIGN KEY (`scout_name`) REFERENCES `scout` (`scout_name`) 
    ON DELETE CASCADE
;

ALTER TABLE `watches` 
 ADD 
	FOREIGN KEY (`report_id`) REFERENCES `scouting_report` (`report_id`) 
    ON DELETE CASCADE
;

ALTER TABLE `works_with` 
 ADD 
	FOREIGN KEY (`coach_name`) REFERENCES `coach` (`coach_name`) 
    ON DELETE CASCADE
;

ALTER TABLE `works_with` 
 ADD 
	FOREIGN KEY (`sd_name`) REFERENCES `sporting_director` (`sd_name`) 
    ON DELETE CASCADE
;

-- Load data from .csv files
LOAD DATA LOCAL INFILE 'E:\\Users\\Bruno Cotrim\\Desktop\\DadosBES\\agent.csv'
INTO TABLE agent
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
;

LOAD DATA LOCAL INFILE 'E:\\Users\\Bruno Cotrim\\Desktop\\DadosBES\\coach.csv'
INTO TABLE coach
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
;

LOAD DATA LOCAL INFILE 'E:\\Users\\Bruno Cotrim\\Desktop\\DadosBES\\financial_info.csv'
INTO TABLE financial_info
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
;


LOAD DATA LOCAL INFILE 'E:\\Users\\Bruno Cotrim\\Desktop\\DadosBES\\player.csv'
INTO TABLE player
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
;


LOAD DATA LOCAL INFILE 'E:\\Users\\Bruno Cotrim\\Desktop\\DadosBES\\provides.csv'
INTO TABLE provides
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
;

LOAD DATA LOCAL INFILE 'E:\\Users\\Bruno Cotrim\\Desktop\\DadosBES\\scout.csv'
INTO TABLE scout
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
;

LOAD DATA LOCAL INFILE 'E:\\Users\\Bruno Cotrim\\Desktop\\DadosBES\\scouting_report.csv'
INTO TABLE scouting_report
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
;

LOAD DATA LOCAL INFILE 'E:\\Users\\Bruno Cotrim\\Desktop\\DadosBES\\sporting_director.csv'
INTO TABLE sporting_director
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
;

LOAD DATA LOCAL INFILE 'E:\\Users\\Bruno Cotrim\\Desktop\\DadosBES\\watches.csv'
INTO TABLE watches
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
;

LOAD DATA LOCAL INFILE 'E:\\Users\\Bruno Cotrim\\Desktop\\DadosBES\\refers_to.csv'
INTO TABLE refers_to
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
;

LOAD DATA LOCAL INFILE 'E:\\Users\\Bruno Cotrim\\Desktop\\DadosBES\\request.csv'
INTO TABLE request
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
;


LOAD DATA LOCAL INFILE 'E:\\Users\\Bruno Cotrim\\Desktop\\DadosBES\\works_with.csv'
INTO TABLE works_with
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
;

-- Define Stored Procedures
DELIMITER $$
CREATE DEFINER=`ist187225`@`%` PROCEDURE minhandling (minstat INT, position VARCHAR(50))
BEGIN
		SELECT P.player_name 
		FROM player AS P, scouting_report AS SR, watches AS W
		WHERE P.player_name = W.player_name AND SR.report_id = W.report_id AND SR.handling>minstat AND P.position = position ;
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE minreflexes (minstat INT, position VARCHAR(50))
BEGIN
		SELECT P.player_name 
		FROM player AS P, scouting_report AS SR, watches AS W
		WHERE P.player_name = W.player_name AND SR.report_id = W.report_id AND SR.reflexes>minstat AND P.position = position ;
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE minshooting (minstat INT, position VARCHAR(50))
BEGIN
		SELECT P.player_name 
		FROM player AS P, scouting_report AS SR, watches AS W
		WHERE P.player_name = W.player_name AND SR.report_id = W.report_id AND SR.shooting>minstat AND P.position = position ;
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE minpassing (minstat INT, position VARCHAR(50))
BEGIN
		SELECT P.player_name 
		FROM player AS P, scouting_report AS SR, watches AS W
		WHERE P.player_name = W.player_name AND SR.report_id = W.report_id AND SR.passing>minstat AND P.position = position ;
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE mintackling (minstat INT, position VARCHAR(50))
BEGIN
		SELECT P.player_name 
		FROM player AS P, scouting_report AS SR, watches AS W
		WHERE P.player_name = W.player_name AND SR.report_id = W.report_id AND SR.tackling>minstat AND P.position = position ;
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE mindribbling (minstat INT, position VARCHAR(50))
BEGIN
		SELECT P.player_name 
		FROM player AS P, scouting_report AS SR, watches AS W
		WHERE P.player_name = W.player_name AND SR.report_id = W.report_id AND SR.dribbling>minstat AND P.position = position ;
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE minleadership (minstat INT, position VARCHAR(50))
BEGIN
		SELECT P.player_name 
		FROM player AS P, scouting_report AS SR, watches AS W
		WHERE P.player_name = W.player_name AND SR.report_id = W.report_id AND SR.leadership>minstat AND P.position = position ;
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE minpositioning (minstat INT, position VARCHAR(50))
BEGIN
		SELECT P.player_name 
		FROM player AS P, scouting_report AS SR, watches AS W
		WHERE P.player_name = W.player_name AND SR.report_id = W.report_id AND SR.positioning>minstat AND P.position = position ;
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE minstrength (minstat INT, position VARCHAR(50))
BEGIN
		SELECT P.player_name 
		FROM player AS P, scouting_report AS SR, watches AS W
		WHERE P.player_name = W.player_name AND SR.report_id = W.report_id AND SR.strength>minstat AND P.position = position ;
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE minstamina (minstat INT, position VARCHAR(50))
BEGIN
		SELECT P.player_name 
		FROM player AS P, scouting_report AS SR, watches AS W
		WHERE P.player_name = W.player_name AND SR.report_id = W.report_id AND SR.stamina>minstat AND P.position = position ;
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE minspeed (minstat INT, position VARCHAR(50))
BEGIN
		SELECT P.player_name 
		FROM player AS P, scouting_report AS SR, watches AS W
		WHERE P.player_name = W.player_name AND SR.report_id = W.report_id AND SR.speed>minstat AND P.position = position ;
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE name_search (player_input VARCHAR(50))
BEGIN
		SELECT P.player_name, P.club, A.agent_name, F.transfer_fee, F.demanded_wage
        FROM player as P, agent as A,provides as PR, financial_info as F
        WHERE P.player_name=PR.player_name and A.agent_name=PR.agent_name and F.contract_id=PR.contract_id
        AND P.player_name=player_input;
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE get_age (player_name VARCHAR(50))
BEGIN
	SELECT TIMESTAMPDIFF(YEAR,P.birth_date,CURDATE())
    FROM player as P
    WHERE P.player_name = player_name;
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE get_contract_time (player_name VARCHAR(50))
BEGIN
	SELECT TIMESTAMPDIFF(YEAR,CURDATE(),FI.contract_expiry_date)
    FROM player as P, financial_info as FI, provides as PR
    WHERE P.player_name = PR.player_name and FI.contract_id=PR.contract_id and P.player_name = player_name;
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE find_under_age (max_age INT)
BEGIN
    SELECT P.player_name, TIMESTAMPDIFF(YEAR,P.birth_date,CURDATE()) AS AGE
    FROM player as P
    WHERE TIMESTAMPDIFF(YEAR,P.birth_date,CURDATE())<=max_age;
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE reffromcoach (sdcheck VARCHAR(50))
BEGIN
        SELECT P.player_name, P.club, A.agent_name, F.transfer_fee, F.demanded_wage
		from player as P, agent as A,provides as PR, financial_info as F, refers_to as R
		where P.player_name=PR.player_name and A.agent_name=PR.agent_name and F.contract_id=PR.contract_id
		and P.player_name=R.player_name and R.sd_name=sdcheck;
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE addnewscreport (ins_rep INT,ins_han INT,ins_ref INT,ins_sho INT,ins_pas INT,ins_tac INT,ins_dri INT,ins_lea INT,ins_pos INT,ins_str INT,ins_sta INT,ins_spe INT)
BEGIN
		insert into scouting_report
        values (ins_rep,ins_han,ins_ref,ins_sho,ins_pas,ins_tac,ins_dri,ins_lea,ins_pos,ins_str,ins_sta,ins_spe);
END$$

DROP PROCEDURE IF EXISTS ist187225.addnewfinancialinfo;
DELIMITER $$
CREATE DEFINER=`ist187225`@`%` PROCEDURE addnewfinancialinfo (ins_con_id INT,ins_con_exp DATE,ins_tra INT,ins_cur INT,ins_dem_wag INT,ins_dem_con INT,ins_sig INT)
BEGIN
		insert into financial_info
        values (ins_con_id,ins_con_exp,ins_tra,ins_cur,ins_dem_wag,ins_dem_con,ins_sig);
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE addnewplayer (player_name VARCHAR(50),position VARCHAR(50),club VARCHAR(50),birth_date DATE,dominant_foot VARCHAR(50),country VARCHAR(50),height INT,weight INT,international_caps INT)
BEGIN
		insert into player
        values (player_name,position,club,birth_date,dominant_foot,country,height,weight,international_caps);
END$$


CREATE DEFINER=`ist187225`@`%` PROCEDURE addnewagent (agent_name VARCHAR(50),phone_number INT,email VARCHAR(50),company VARCHAR(50), pass VARCHAR(50))
BEGIN
		insert into agent
        values (agent_name,phone_number,email,company, pass);
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE addnewcoach (coach_name VARCHAR(50),pass VARCHAR(50))
BEGIN
		insert into coach
        values (coach_name, pass);
END$$


CREATE DEFINER=`ist187225`@`%` PROCEDURE addnewprovides (agent_name VARCHAR(50), contract_id INT, player_name VARCHAR(50), agent_fee INT)
BEGIN
		insert into provides
        values (agent_name, contract_id, player_name, agent_fee);
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE addnewrefers_to (coach_name VARCHAR(50), sd_name VARCHAR(50), player_name VARCHAR(50))
BEGIN
		insert into refers_to
        values (coach_name, sd_name, player_name);
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE addnewrequest (position_in VARCHAR(50), coach_name_in VARCHAR(50), scout_name_in VARCHAR(50), p_requerirements_in VARCHAR(200))
BEGIN
if (select request.request_id from request) then
		insert into request (request_id,position,coach_name,scout_name,p_requirements)
        SELECT max(request.request_id)+1, position_in, coach_name_in, scout_name_in, p_requerirements_in
        FROM request;
else
		insert into request (request_id,position,coach_name,scout_name,p_requirements)
        SELECT 1, position_in, coach_name_in, scout_name_in, p_requerirements_in
        FROM request;
end if;
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE addnewscout (scout_name VARCHAR(50), league VARCHAR(50), country VARCHAR(50), pass VARCHAR(50))
BEGIN
		insert into scout
        values (scout_name, league, country,pass);
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE addnewsporting_director (sd_name VARCHAR(50),pass VARCHAR(50))
BEGIN
		insert into sporting_director
        values (sd_name,pass);
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE addnewworks_with (coach_name VARCHAR(50),sd_name VARCHAR(50))
BEGIN
		insert into works_with
        values (coach_name,sd_name);
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE addnewwatches (scout_name VARCHAR(50), report_id INT, player_name VARCHAR(50))
BEGIN
		insert into watches
        values (scout_name, report_id, player_name);
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE gk_rating (player_name_in VARCHAR(50))
BEGIN
		SELECT (sdr.handling+sdr.reflexes)/2 as goalkeeper_rating
        FROM scouting_report as sdr, player as P, watches as W
        WHERE P.player_name=player_name_in and P.player_name=W.player_name and W.report_id=sdr.report_id;
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE tech_rating (player_name_in VARCHAR(50))
BEGIN
		SELECT (sdr.shooting+sdr.dribbling+sdr.passing+sdr.tackling)/4 as technical_rating
        FROM scouting_report as sdr, player as P, watches as W
        WHERE P.player_name=player_name_in and P.player_name=W.player_name and W.report_id=sdr.report_id;
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE ment_rating (player_name_in VARCHAR(50))
BEGIN
		SELECT (sdr.leadership+sdr.positioning+sdr.stamina)/3 as mental_rating
        FROM scouting_report as sdr, player as P, watches as W
        WHERE P.player_name=player_name_in and P.player_name=W.player_name and W.report_id=sdr.report_id;
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE phys_rating (player_name_in VARCHAR(50))
BEGIN
		SELECT (sdr.strength+sdr.speed)/2 as physical_rating
        FROM scouting_report as sdr, player as P, watches as W
        WHERE P.player_name=player_name_in and P.player_name=W.player_name and W.report_id=sdr.report_id;
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE sc_report_info (player_name_in VARCHAR(50))
BEGIN
		SELECT SCR.handling, SCR.reflexes, SCR.shooting, SCR.passing, SCR.tackling, SCR.dribbling, SCR.leadership, SCR.positioning, SCR.strength, SCR.stamina, SCR.speed
        FROM player as P, watches as W, scouting_report as SCR
        WHERE P.player_name=W.player_name and SCR.report_id=W.report_id and P.player_name=player_name_in;
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE bio_info (player_name_in VARCHAR(50))
BEGIN
		SELECT P.position, P.club, P.birth_date, P.dominant_foot, P.country, P.height, P.weight, P.international_caps
        FROM player as P 
        WHERE P.player_name=player_name_in;
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE agent_info (player_name_in VARCHAR(50))
BEGIN
		SELECT A.agent_name, A.phone_number, A.email, A.company, PR.agent_fee
        FROM player as P, provides as PR, agent as A
        WHERE P.player_name=player_name_in and P.player_name=PR.player_name and PR.agent_name=A.agent_name;
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE financial_info (player_name_in VARCHAR(50))
BEGIN
		SELECT F.transfer_fee, F.signing_fee, F.current_wage, F.contract_expiry_date, F.demanded_wage, F.demanded_contract_length
        FROM player as P, provides as PR, financial_info as F
        WHERE P.player_name=player_name_in and P.player_name=PR.player_name and PR.contract_id=F.contract_id;
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE init_query ()
BEGIN
		CREATE TABLE i (SELECT P.player_name,P.club,A.agent_name,FI.transfer_fee, FI.demanded_wage, FI.signing_fee, PR.agent_fee, SR.handling, SR.reflexes, SR.shooting, SR.passing, SR.tackling, SR.dribbling, SR. leadership, SR.positioning, SR.strength, SR.stamina, SR.speed, P.dominant_foot, P.position, P.birth_date
		FROM player as P,agent as A, provides as PR, financial_info as FI, watches as W, scouting_report as SR
		WHERE P.player_name = PR.player_name AND PR.contract_id=FI.contract_id AND A.agent_name = PR.agent_name
		AND P.player_name = W.player_name AND W.report_id = SR.report_id);

END$$


CREATE DEFINER=`ist187225`@`%` PROCEDURE get_coach_name (sd_name_in VARCHAR(50))
BEGIN
		SELECT W.coach_name
        FROM works_with as W
        WHERE W.sd_name=sd_name_in;

END$$


CREATE DEFINER=`ist187225`@`%` PROCEDURE get_sd_name (coach_name_in VARCHAR(50))
BEGIN
		SELECT W.sd_name
        FROM works_with as W
        WHERE W.coach_name=coach_name_in;

END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE getplayerscout (player_name_in VARCHAR(50))
BEGIN
		SELECT w.scout_name,w.report_id,w.player_name
		FROM watches as w
		WHERE w.player_name = player_name_in;
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE getscoutvector ()
BEGIN
		SELECT S.scout_name
		FROM scout as S;
END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE getrequests (scout_name_in VARCHAR(50))
BEGIN
		SELECT R.coach_name, R.position, R.p_requirements
		FROM request as R 
		WHERE R.scout_name=scout_name_in;

END$$

/*Edit Tables*/

CREATE DEFINER=`ist187225`@`%` PROCEDURE editscreport (ins_rep_id INT,ins_han INT,ins_ref INT,ins_sho INT,ins_pas INT,ins_tac INT,ins_dri INT,ins_lea INT,ins_pos INT,ins_str INT,ins_sta INT,ins_spe INT)
BEGIN
		UPDATE scouting_report
		SET handling=ins_han,reflexes=ins_ref,shooting=ins_sho,passing=ins_pas,tackling=ins_tac,dribbling=ins_dri,leadership=ins_lea,positioning=ins_pos,strength=ins_str,stamina=ins_sta,speed=ins_spe
		WHERE report_id=ins_rep_id;

END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE editfinancialinfo (ins_contract_id INT,ins_contract_exp DATE,ins_transf_fee INT,ins_current_wage INT,ins_demanded_wage INT,ins_demand_contract_l INT,ins_sig_fee INT)
BEGIN
		UPDATE financial_info
		SET contract_id=ins_contract_id,contract_expiry_date=ins_contract_exp,transfer_fee=ins_transf_fee,current_wage=ins_current_wage,demanded_wage=ins_demanded_wage,demanded_contract_length=ins_demand_contract_l,signing_fee=ins_sig_fee
		WHERE contract_id=ins_contract_id;

END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE editplayer (ins_player_name VARCHAR(50),ins_position VARCHAR(50),ins_club VARCHAR(50),ins_birth_date DATE,ins_dominant_foot VARCHAR(50),ins_country VARCHAR(50),ins_height INT, ins_weight INT, ins_ic INT)
BEGIN
		UPDATE player
		SET position=ins_position,club=ins_club,birth_date=ins_birth_date,dominant_foot=ins_dominant_foot,country=ins_country,height=ins_height,weight=ins_weight, international_caps=ins_ic
		WHERE player_name=ins_player_name;

END$$

CREATE DEFINER=`ist187225`@`%` PROCEDURE editagentfee (ins_contract_id INT, ins_agent_fee INT)
BEGIN
        UPDATE provides
        SET agent_fee=ins_agent_fee
        WHERE contract_id=ins_contract_id;

END$$


CREATE DEFINER=`ist187225`@`%` PROCEDURE removeplayer (ins_player_name VARCHAR(50))
BEGIN
        DELETE FROM player
        WHERE player_name=ins_player_name;

END$$

DELIMITER ;