//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by V2.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_V2_DIALOG                   102
#define IDI_ICON1                       128
#define IDR_MAINFRAME                   129
#define IDD_COACHLOGDIALOG              130
#define IDD_SPORTDLOGDIALOG             131
#define IDD_SCOUTLOGDIALOG              132
#define IDD_AGENTDIALOG                 133
#define IDD_COACHMENUDIALOG             134
#define IDD_SCOUTMENUDIALOG             135
#define IDD_SPORTDMENUDIALOG            136
#define IDD_AGENTMENUDIALOG             137
#define IDD_SEARCHPLAYER                138
#define IDD_Player_Info_Table           140
#define IDD_ADDNEWPLAYER                142
#define IDD_REFDPLAYERS                 144
#define IDD_EDITPLAYER                  146
#define IDD_REQUEST                     148
#define IDD_REQSTPLAYERS                150
#define IDC_COACHBUTTON                 1000
#define IDC_SPORTDBUTTON                1001
#define IDC_SCOUTBUTTON                 1002
#define IDC_AGENTBUTTON                 1003
#define IDC_USERNAME                    1006
#define IDC_PASSWORD                    1007
#define IDC_LOGIN                       1008
#define IDC_BUTTON1                     1010
#define IDC_BUTTON2                     1011
#define IDC_LOGOUT                      1012
#define IDC_BUTTON3                     1013
#define IDC_CREATEP                     1014
#define IDC_PERSONELINFO                1015
#define IDC_EDIT1                       1016
#define IDC_EDIT_Player_Name_Search     1016
#define IDC_EDIT2goalkeeper_rating      1016
#define IDC_PNAME                       1016
#define IDC_WELCOMEMESSAGE              1017
#define IDC_EDIT_Player_Name_Search2    1017
#define IDC_PlayerList                  1018
#define IDC_BUTTON_players              1019
#define IDC_EDIT1technical_rating       1020
#define IDC_EDIT_Player_Name_Search3    1020
#define IDC_EDIT2mental_rating          1021
#define IDC_EDIT_Player_Name_Search4    1021
#define IDC_LIST1agent_info             1022
#define IDC_EDIT_Player_Name_Search5    1022
#define IDC_LIST3tch_rating             1023
#define IDC_EDIT_Player_Name_Search6    1023
#define IDC_LIST4mental_rating          1024
#define IDC_EDIT_Player_Name_Search7    1024
#define IDC_EDIT_Player_Name_Search8    1025
#define IDC_LIST2goalkeeper_rating      1026
#define IDC_EDIT_Player_Name_Search9    1026
#define IDC_LIST1bio_info               1027
#define IDC_EDIT_Player_Name_Search10   1027
#define IDC_LIST2_financial_info        1028
#define IDC_EDIT_Player_Name_Search11   1028
#define IDC_EDIT1player_name            1029
#define IDC_EDIT_Player_Name_Search12   1029
#define IDC_EDIT5                       1030
#define IDC_EDIT_Player_Name_Search13   1030
#define IDC_LIST5                       1031
#define IDC_EDIT_Player_Name_Search14   1031
#define IDC_EFSF                        1031
#define IDC_PDBD                        1032
#define IDC_EDIT_Player_Name_Search15   1032
#define IDC_EFAF                        1032
#define IDC_PBDM                        1033
#define IDC_EDIT_Player_Name_Search16   1033
#define IDC_PBDY                        1034
#define IDC_EDIT_Player_Name_Search17   1034
#define IDC_PCOUNTRY                    1035
#define IDC_EDIT_Player_Name_Search18   1035
#define IDC_PPOSITION                   1036
#define IDC_PCLUB                       1037
#define IDC_PHEIGHT                     1038
#define IDC_PWEIGHT                     1039
#define IDC_PFOOTL                      1040
#define IDC_PFOOTB                      1041
#define IDC_PFOOTR                      1042
#define IDC_PIC                         1043
#define IDC_CONFIRMDATA                 1044
#define IDC_CHECK1                      1045
#define IDC_CHECK2                      1046
#define IDC_BUTTONRefered               1046
#define IDC_CHECK3                      1047
#define IDC_WELCOME                     1047
#define IDC_CHECK4                      1048
#define IDC_CHECK5                      1049
#define IDC_LIST1                       1049
#define IDC_CHECK6                      1050
#define IDC_CHECK7                      1051
#define IDC_CHECK8                      1052
#define IDC_CHECK9                      1053
#define IDC_PDBD1                       1053
#define IDC_CHECK10                     1054
#define IDC_CHECK11                     1055
#define IDC_CHECK12                     1056
#define IDC_CHECK13                     1057
#define IDC_CHECK14                     1058
#define IDC_CHECK15                     1059
#define IDC_CHECK16                     1060
#define IDC_CHECK17                     1061
#define IDC_CHECK18                     1062
#define IDC_EPHAND                      1063
#define IDC_EPREF                       1064
#define IDC_EPPASS                      1065
#define IDC_EFCDD                       1066
#define IDC_EFCDM                       1067
#define IDC_EFCDY                       1068
#define IDC_EFNCL                       1069
#define IDC_EFCW                        1070
#define IDC_EFNW                        1071
#define IDC_EPSHOOT                     1072
#define IDC_EPDRIB                      1073
#define IDC_EPPOS                       1074
#define IDC_EPSPD                       1075
#define IDC_EPSTAM                      1076
#define IDC_EPSTGH                      1077
#define IDC_EPTACK                      1078
#define IDC_EPLEAD                      1079
#define IDC_SEARCH                      1080
#define IDC_EFTF                        1081
#define IDC_PREQ                        1082
#define IDC_COMBO1                      1083
#define IDC_STATICref                   1084
#define IDC_POS                         1085
#define IDC_STATICpos                   1086
#define IDC_NREQ                        1087
#define IDC_BUTTONSEEREQ                1088
#define IDC_LISTREQ                     1089
#define IDC_RICHEDIT21                  1090

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        155
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
